// <auto-generated />
using System;
using EPOLIS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPOLIS.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20201017072447_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPOLIS.Models.Penutupan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADMINID")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("CIF")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("ISBROKER")
                        .HasColumnType("int")
                        .HasMaxLength(20);

                    b.Property<int>("ISUPDATEPENUTUPANRENEWAL")
                        .HasColumnType("int");

                    b.Property<string>("JENISPENUTUPAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMA")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NOPK")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NOREGPENUTUPAN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NOSKK")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<DateTime>("TGLINPUT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TGLOTORISASI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TGLSKK")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATEBY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATEDATE")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Penutupans");
                });
#pragma warning restore 612, 618
        }
    }
}
