// <auto-generated />
using System;
using EPOLIS.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPOLIS.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPOLIS.Models.FormPenutupan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ALAMATNASABAH")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JENISASURANSI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JENISPENUTUPAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOFASILITAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NOFAX")
                        .HasColumnType("int");

                    b.Property<int>("NOHP")
                        .HasColumnType("int");

                    b.Property<DateTime>("NONASABAH")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOREGPENUTUPAN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("NOREKENING")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOSKK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OKUPASI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PEKERJAAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEGMENTASI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELPRUMAH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATEDATE")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FormPenutupan");
                });

            modelBuilder.Entity("EPOLIS.Models.Penutupan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADMINID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ISBROKER")
                        .HasColumnType("int");

                    b.Property<int>("ISUPDATEPENUTUPANRENEWAL")
                        .HasColumnType("int");

                    b.Property<string>("JENISPENUTUPAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOPK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOREGPENUTUPAN")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NOSKK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TGLINPUT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TGLOTORISASI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TGLSKK")
                        .HasColumnType("datetime2");

                    b.Property<string>("UPDATEBY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATEDATE")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Penutupans");
                });
#pragma warning restore 612, 618
        }
    }
}
